language: generic

sudo: required

services:
  - docker 

before-install:
  - docker run -t michaelbr95/docker-react -f Dockerfile.dev

script:
  - docker run -e CI=true michaelbr95/docker-react npm run test